In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [127]:
from sklearn.datasets import make_blobs

In [128]:
data = make_blobs(n_samples=300, n_features=5, centers=2, cluster_std=6.0)

In [129]:
data

(array([[-16.33411667,  -0.75265951,  22.76509344,  -5.99997055,
          -8.02097811],
        [ -2.20675273,  -3.88531383,  -6.65858371,  -0.81770018,
          14.66564478],
        [  0.07663377,   0.49859949,  -7.4861778 ,  16.40268538,
          -0.17235386],
        ...,
        [ -6.81749621,   4.35890097,   5.07773305,  17.35797071,
           8.61044208],
        [ -7.02776315,  -1.92359702,   3.64777836,   9.50314453,
         -10.74876294],
        [ -9.0176151 ,   1.01468209,  16.58063835,  -6.05792705,
         -16.76489088]]),
 array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
        0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
        0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
        1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
        0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       

In [130]:
df_feat = pd.DataFrame(data[0], columns=['feature_' + str(i) for i in range(1, 6)])

In [131]:
df_feat

feature_1  feature_2  feature_3  feature_4  feature_5
0   -16.334117  -0.752660  22.765093  -5.999971  -8.020978
1    -2.206753  -3.885314  -6.658584  -0.817700  14.665645
2     0.076634   0.498599  -7.486178  16.402685  -0.172354
3    -2.103419 -12.482265   6.475674   5.624540   5.567097
4    -6.142997  -7.694793   0.484010   8.559090   7.359101
..         ...        ...        ...        ...        ...
295  -3.086040  -0.738464  -6.870873  12.207558  12.794458
296 -13.609307  -1.398475  11.204978   7.556369  -7.370613
297  -6.817496   4.358901   5.077733  17.357971   8.610442
298  -7.027763  -1.923597   3.647778   9.503145 -10.748763
299  -9.017615   1.014682  16.580638  -6.057927 -16.764891

[300 rows x 5 columns]

In [132]:
y = data[1]

In [133]:
y

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1])

In [134]:
from sklearn.preprocessing import MinMaxScaler

In [135]:
scaler = MinMaxScaler()

In [136]:
X = scaler.fit_transform(df_feat)

In [137]:
from sklearn.model_selection import train_test_split

In [138]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [139]:
from sklearn.neighbors import KNeighborsClassifier

In [140]:
knn = KNeighborsClassifier(n_neighbors=1)

In [141]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [142]:
predictions = knn.predict(X_test)

In [143]:
predictions

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1])

In [144]:
from sklearn.metrics import confusion_matrix, classification_report

In [145]:
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

[[47  1]
 [ 2 40]]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97        48
           1       0.98      0.95      0.96        42

    accuracy                           0.97        90
   macro avg       0.97      0.97      0.97        90
weighted avg       0.97      0.97      0.97        90



In [146]:
error_rate = []

for i in range(1, 40):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, y_train)
    pred_i = knn.predict(X_test)
    
    error_rate.append(np.mean(pred_i != y_test))
    

In [147]:
plt.figure(figsize=(10, 6))

plt.plot(range(1, 40), error_rate, color='blue', linestyle='--', markersize=10, markerfacecolor='red', marker='o')

plt.title('K versus Error rate')

plt.xlabel('K')
plt.ylabel('Error rate')

Text(0, 0.5, 'Error rate')

In [148]:
# lowest error rate= 5

In [149]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)


print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

[[48  0]
 [ 0 42]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        48
           1       1.00      1.00      1.00        42

    accuracy                           1.00        90
   macro avg       1.00      1.00      1.00        90
weighted avg       1.00      1.00      1.00        90



In [150]:
# correctly classifying all point now!

In [161]:
features = pd.DataFrame(data=data[0], columns=['feature_' + str(i) for i in range(1, 6)])

In [162]:
lables = pd.DataFrame(data[1], columns=['labels'])

In [163]:
dataset = pd.concat([features, lables], axis=1)

In [166]:
dataset.head(1)

feature_1  feature_2  feature_3  feature_4  feature_5  labels
0 -16.334117   -0.75266  22.765093  -5.999971  -8.020978       1

In [188]:
data_point_1 = scaler.transform(np.array(dataset.iloc[0][:-1]).reshape(-1, 5))

In [190]:
knn.predict(data_point_1)[0]

1